[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; img-src 'self' data:; media-src 'self' https://www.youtube.com https://player.vimeo.com; frame-src https://www.youtube.com https://player.vimeo.com https://www.google.com https://maps.googleapis.com https://maps.gstatic.com https://google.fr"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/alexchesnay"
  status = 301

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/alexchesnay"
  status = 301

[[redirects]]
  from = "/services.html"
  to = "/services/"
  status = 301

[[redirects]]
  from = "/a-propos.html"
  to = "/a-propos/"
  status = 301

[[redirects]]
  from = "/work"
  to = "/projets/"
  status = 301

[[redirects]]
  from = "/work/"
  to = "/projets/"
  status = 301

[[redirects]]
  from = "/projects"
  to = "/projets/"
  status = 301

[[redirects]]
  from = "/mentions-legales.html"
  to = "/mentions-legales"
  status = 301

[[redirects]]
  from = "/politique-confidentialite.html"
  to = "/politique-de-confidentialite"
  status = 301

[[redirects]]
  from = "/animation-3d.html"
  to = "/animation-3d"
  status = 301

[[redirects]]
  from = "/animation-2d.html"
  to = "/animation-2d"
  status = 301

[[redirects]]
  from = "/vfx.html"
  to = "/vfx"
  status = 301

[[redirects]]
  from = "/virtual-reality.html"
  to = "/virtual-reality"
  status = 301

[[notifications]]
  type = "form_submission"
  to = "alex-mennechet@outlook.fr"
  [notifications.conditions]
    form = "contact"
