name: Repository Backup

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create archive
        run: tar -czf repo-backup.tar.gz .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-backup
          path: repo-backup.tar.gz
